
type User {
    name: String!
    email: String! @unique
    address: String!
    orders: [Order!]! @relation
}

type Order {
    orders: [Placement]!
    totalPrice: Float!
    tax: Float!
    price: Float!
    userId: String!
    user: User!
    date: Date!
}

type Placement @embedded {
    quantity: Int!,
    food: Memu
}


type Memu {
    name: String!
    photo: String!
    price: Float!
    description: String
    vegan: Boolean
    restaurantId: String!
    restaurant: Restaurant!
}

type Restaurant {
    name: String!
    logo: String!
    description: String
    memus: [Memu!]! @relation
}

type Query {
    allRestaurants: [Restaurant!]!
    getRestaurants(name: String!): Memu
    allUsers: [User!]!
    getUserByName(email: String!): Memu
    allOrders: [Order!]!
    allMemus: [Memu!]!
}